<!--<button id="test_btn">TEST BTN</button>-->

<button id="test_btn">TEST BTN</button>

<div id="popup-modal">
    This is Test JS
</div>

<!--Use data-mage-init-->

<!--<div data-mage-init='{"Tigren_JavascriptInitExample/js/script":{}}'>-->
<!--    This is Test JS-->
<!--</div>-->

<!--Use x-magento-init-->

<script type="text/x-magento-init">
    {
        "#test_btn": {
            "modal/test": {
                "config": "value"
            }
        }
    }
</script>
